meta:
  title: Inside REACT-VFX
  thumbnail: slides/logo.png
  description:
  sns:
    - twitter
slide:
  loop: true
  sidebar: true
  targetBlank: true
  showIndex: true
  isVertical: false
  code:
    languages:
      - javascript
      - typescript
      - jsx
      - tsx
    plugins: []
    theme: okaidia
  chart: false
  math: false
extends:
  js: ./index.js
  css: ./style.css
  webpack:
build:
  ssr: true
