meta:
  title: Inside REACT-VFX
  thumbnail: slides/ogimage.png
  description: REACT-VFXの実装について解説
  siteName: amagi.dev
  sns:
    - twitter
    - hatena
slide:
  loop: true
  sidebar: true
  targetBlank: true
  showIndex: false
  isVertical: false
  code:
    languages:
      - javascript
      - typescript
      - jsx
      - tsx
    plugins: []
    theme: okaidia
  chart: false
  math: false
extends:
  js: ./index.js
  css: ./style.css
  webpack: ./webpack.config.js
build:
  ssr: true
